apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: {{  .Values.image.repository  }}:{{ .Values.image.tag }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.request.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        livenessProbe:
          httpGet:
            port: {{ .Values.livenessProbe.port }}
            path: {{ .Values.livenessProbe.path }}
        readinessProbe:
          httpGet:
            port: {{ .Values.readinessProbe.port }}
            path: {{ .Values.readinessProbe.path }}
          
          

