apiVersion: v1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alxfmpl/nd064_course_1
    targetRevision: HEAD
    path: project/helm
    helm:
      valueFiles:
      - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
